"""Finalize Tableau-ready football outputs and documentation.

This script is the final preparation layer for the post-match Tableau package.
It keeps the analytical outputs generated by earlier phases, adds consistent
metadata fields, creates missing event/shot/possession views, and writes a data
dictionary plus calculated-field guide for Tableau.

Inputs:
    outputs/clean_events.csv
    outputs/clean_games.csv
    outputs/player_lookup.csv
    outputs/tableau_*.csv from prior phases, when available

Outputs:
    outputs/tableau_match_summary.csv
    outputs/tableau_team_period_metrics.csv
    outputs/tableau_team_zone_metrics.csv
    outputs/tableau_player_metrics.csv
    outputs/tableau_player_profiles.csv
    outputs/tableau_event_map.csv
    outputs/tableau_shots.csv
    outputs/tableau_possession_sequences.csv
    outputs/tableau_momentum_timeline.csv
    outputs/tableau_insight_flags.csv
    outputs/tableau_tracking_team_shape.csv, if present
    outputs/tableau_tracking_player_physical.csv, if present
    docs/tableau_data_dictionary.md
    docs/tableau_calculated_fields.md
"""

from __future__ import annotations

import csv
import math
import re
from collections import Counter, defaultdict
from pathlib import Path
from statistics import mean
from typing import Any


ROOT = Path(__file__).resolve().parents[1]
OUTPUTS = ROOT / "outputs"
DOCS = ROOT / "docs"

EVENTS_FILE = OUTPUTS / "clean_events.csv"
GAMES_FILE = OUTPUTS / "clean_games.csv"
PLAYER_LOOKUP_FILE = OUTPUTS / "player_lookup.csv"

FINAL_THIRD_X = 18.67
BOX_X = 39.5
BOX_HALF_WIDTH = 20.16
PROGRESSIVE_GAIN_M = 10.0

REQUIRED_OUTPUTS = [
    "tableau_match_summary.csv",
    "tableau_team_period_metrics.csv",
    "tableau_team_zone_metrics.csv",
    "tableau_player_metrics.csv",
    "tableau_player_profiles.csv",
    "tableau_event_map.csv",
    "tableau_shots.csv",
    "tableau_possession_sequences.csv",
    "tableau_momentum_timeline.csv",
    "tableau_insight_flags.csv",
]

OPTIONAL_TRACKING_OUTPUTS = [
    "tableau_tracking_team_shape.csv",
    "tableau_tracking_player_physical.csv",
]


def snake_case(name: str) -> str:
    value = re.sub(r"[^0-9A-Za-z]+", "_", str(name).strip())
    value = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    value = re.sub(r"([A-Z]+)([A-Z][a-z])", r"\1_\2", value)
    value = re.sub(r"_+", "_", value).strip("_").lower()
    return value or "unnamed"


def unique_names(names: list[str]) -> list[str]:
    seen: dict[str, int] = {}
    result = []
    for name in names:
        base = snake_case(name)
        count = seen.get(base, 0)
        seen[base] = count + 1
        result.append(base if count == 0 else f"{base}_{count + 1}")
    return result


def read_csv(path: Path, normalize_headers: bool = True) -> tuple[list[str], list[dict[str, str]]]:
    if not path.exists():
        return [], []
    with path.open("r", newline="", encoding="utf-8-sig") as handle:
        reader = csv.reader(handle)
        try:
            header = next(reader)
        except StopIteration:
            return [], []
        fields = unique_names(header) if normalize_headers else header
        rows: list[dict[str, str]] = []
        for raw in reader:
            row = {}
            for idx, field in enumerate(fields):
                row[field] = clean_cell(raw[idx]) if idx < len(raw) else ""
            rows.append(row)
    return fields, rows


def write_csv(path: Path, fields: list[str], rows: list[dict[str, Any]]) -> None:
    fields = unique_names(fields)
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fields, extrasaction="ignore")
        writer.writeheader()
        for row in rows:
            writer.writerow({field: clean_cell(row.get(field, "")) for field in fields})


def clean_cell(value: Any) -> str:
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if not math.isfinite(value):
            return ""
        return f"{value:.4f}".rstrip("0").rstrip(".")
    text = str(value).strip()
    text = re.sub(r"\s+", " ", text)
    return text


def num(value: Any) -> float | None:
    if value in ("", None):
        return None
    try:
        number = float(str(value).replace("%", "").replace(",", ""))
    except (TypeError, ValueError):
        return None
    return number if math.isfinite(number) else None


def truthy(value: Any) -> bool:
    return str(value).strip().lower() == "true"


def safe_round(value: Any, digits: int = 4) -> float | str:
    number = num(value)
    if number is None:
        return ""
    return round(number, digits)


def is_action(row: dict[str, str]) -> bool:
    return row.get("is_blank_event") != "true" and bool(row.get("team_name"))


def is_pass(row: dict[str, str]) -> bool:
    return row.get("coord_source") == "pass_loc" or bool(row.get("passer_id"))


def is_completed(row: dict[str, str]) -> bool:
    return truthy(row.get("raw_completed")) or row.get("outcome") == "completed_pass"


def is_shot(row: dict[str, str]) -> bool:
    return bool(row.get("shooter_id")) or bool(row.get("shot_outcome")) or row.get("coord_source") == "shot_loc"


def is_shot_row_preferred(row: dict[str, str]) -> bool:
    return bool(row.get("shooter_id")) or row.get("coord_source") == "shot_loc"


def is_shot_on_target(row: dict[str, str]) -> bool:
    outcome = row.get("shot_outcome") or row.get("raw_shot_outcome")
    return outcome in {"goal", "save"}


def is_goal(row: dict[str, str]) -> bool:
    return row.get("shot_outcome") == "goal" or row.get("raw_shot_outcome") == "goal" or truthy(row.get("raw_is_scored"))


def is_final_third(row: dict[str, str]) -> bool:
    x = num(row.get("x_oriented"))
    return x is not None and x > FINAL_THIRD_X


def ends_final_third(row: dict[str, str]) -> bool:
    x = num(row.get("end_x_oriented"))
    return x is not None and x > FINAL_THIRD_X


def is_box(row: dict[str, str]) -> bool:
    x = num(row.get("x_oriented"))
    y = abs(num(row.get("y_oriented")) or 999)
    end_x = num(row.get("end_x_oriented"))
    end_y = abs(num(row.get("end_y_oriented")) or 999)
    start_box = x is not None and x >= BOX_X and y <= BOX_HALF_WIDTH
    end_box = end_x is not None and end_x >= BOX_X and end_y <= BOX_HALF_WIDTH
    return start_box or end_box or truthy(row.get("is_box"))


def vertical_gain(row: dict[str, str]) -> float:
    start = num(row.get("x_oriented"))
    end = num(row.get("end_x_oriented"))
    if start is None or end is None:
        return 0.0
    return max(0.0, end - start)


def is_progressive(row: dict[str, str]) -> bool:
    return is_completed(row) and vertical_gain(row) >= PROGRESSIVE_GAIN_M


def is_recovery(row: dict[str, str]) -> bool:
    labels = {
        row.get("start_type"),
        row.get("turnover_type"),
        row.get("outcome"),
        row.get("raw_interception_type"),
    }
    return bool(labels & {"recovery", "interception", "tackle", "shot_recovered", "anticipated", "reacted", "passive"})


def is_loss(row: dict[str, str]) -> bool:
    return truthy(row.get("is_turnover")) or row.get("outcome") in {"turnover", "ball_lost", "lost_ball"}


def threat_weight(x: float | None, y: float | None) -> float:
    if x is None:
        return 0.0
    abs_y = abs(y if y is not None else 99.0)
    if x >= BOX_X and abs_y <= BOX_HALF_WIDTH:
        return 0.18
    if x > FINAL_THIRD_X:
        return 0.08
    if x >= -FINAL_THIRD_X:
        return 0.03
    return 0.01


def threat_value(row: dict[str, str]) -> float:
    xg = num(row.get("xg"))
    if is_shot(row) and xg is not None:
        return xg
    start_x = num(row.get("x_oriented"))
    start_y = num(row.get("y_oriented"))
    end_x = num(row.get("end_x_oriented"))
    end_y = num(row.get("end_y_oriented"))
    if end_x is None:
        return 0.0
    return max(0.0, threat_weight(end_x, end_y) - threat_weight(start_x, start_y))


def first_non_blank(*values: Any) -> str:
    for value in values:
        text = clean_cell(value)
        if text:
            return text
    return ""


def metric_unit(metric_name: str) -> str:
    metric = metric_name.lower()
    if metric.endswith("_per_90") or "per_90" in metric:
        return "per_90"
    if any(token in metric for token in ["share", "rate", "pct", "percentage", "field_tilt", "possession_proxy", "completion"]):
        return "share"
    if any(token in metric for token in ["xg", "threat", "danger_index", "momentum_index"]):
        return "index"
    if any(token in metric for token in ["distance", "width", "depth", "height", "compactness", "gained"]):
        return "meters"
    if any(token in metric for token in ["speed", "velocity"]):
        return "m_per_s"
    if any(token in metric for token in ["duration", "second"]):
        return "seconds"
    if "minute" in metric:
        return "minutes"
    return "count"


def dashboard_section(metric_name: str, file_name: str = "") -> str:
    metric = metric_name.lower()
    file_name = file_name.lower()
    if "player" in file_name:
        return "Player Impact"
    if "tracking" in file_name:
        return "Tracking & Team Shape"
    if "shot" in file_name or any(token in metric for token in ["shot", "xg", "threat", "danger", "box", "key_pass"]):
        return "Chance Creation & Final Third"
    if any(token in metric for token in ["loss", "recovery", "interception", "tackle", "ppda", "press"]):
        return "Defensive Behaviour & Transitions"
    if any(token in metric for token in ["progressive", "vertical", "sequence", "directness", "entry"]):
        return "Territory & Control"
    if any(token in metric for token in ["field_tilt", "possession", "territory", "action_height", "attacking_third"]):
        return "Territory & Control"
    if "momentum" in file_name:
        return "Executive Match Overview"
    if "insight" in file_name:
        return "Executive Match Overview"
    return "Executive Match Overview"


def recommended_chart_type(file_name: str, metric_name: str = "") -> str:
    file_name = file_name.lower()
    metric = metric_name.lower()
    if "event_map" in file_name:
        return "pitch scatter map"
    if "shots" in file_name:
        return "shot map"
    if "zone" in file_name:
        return "pitch heatmap"
    if "period" in file_name:
        return "grouped bar chart"
    if "momentum" in file_name:
        return "dual-axis timeline"
    if "player_profiles" in file_name:
        return "profile table"
    if "player_metrics" in file_name:
        return "ranked bar chart"
    if "possession" in file_name:
        return "sequence table and scatter"
    if "tracking_team_shape" in file_name:
        return "time-series line chart"
    if "tracking_player_physical" in file_name:
        return "ranked bar chart"
    if "insight" in file_name:
        return "annotation table"
    if any(token in metric for token in ["field_tilt", "possession", "share"]):
        return "share bar"
    return "KPI card"


def priority_level(metric_name: str, file_name: str = "") -> str:
    metric = metric_name.lower()
    file_name = file_name.lower()
    high_tokens = [
        "field_tilt",
        "possession_proxy",
        "shots",
        "xg",
        "threat",
        "box_entries",
        "danger",
        "progressive_passes",
        "dangerous_losses",
        "momentum",
        "team_width",
        "team_depth",
        "compactness",
    ]
    if "insight" in file_name:
        return "high"
    if any(token in metric for token in high_tokens):
        return "high"
    if any(token in metric for token in ["total_actions", "minutes", "distance", "speed", "sequence"]):
        return "medium"
    return "medium"


def add_tableau_metadata(rows: list[dict[str, Any]], file_name: str) -> list[dict[str, Any]]:
    out = []
    for row in rows:
        clean = {snake_case(k): clean_cell(v) for k, v in row.items()}
        metric = first_non_blank(clean.get("metric_name"), clean.get("insight_type"), clean.get("primary_profile"), file_name)
        clean.setdefault("metric_unit", metric_unit(metric))
        clean.setdefault("interpretation_label", "")
        clean.setdefault("insight_text", "")
        clean["dashboard_section"] = first_non_blank(clean.get("dashboard_section"), dashboard_section(metric, file_name))
        clean["recommended_chart_type"] = first_non_blank(clean.get("recommended_chart_type"), recommended_chart_type(file_name, metric))
        clean["priority_level"] = first_non_blank(clean.get("priority_level"), priority_level(metric, file_name))
        out.append(clean)
    return out


def preferred_field_order(fields: list[str]) -> list[str]:
    first = [
        "match_id",
        "game_id_opta",
        "event_id",
        "poss_id",
        "team_id",
        "team_name",
        "team",
        "opponent_team_id",
        "opponent_team_name",
        "opponent",
        "period",
        "period_second",
        "match_second",
        "match_minute",
        "minute_bin",
        "minute_bin_5",
        "minute_bin_10",
        "player_id",
        "player_name",
        "metric_group",
        "metric_name",
        "metric_value",
        "metric_unit",
        "zone",
        "third",
        "channel",
        "x",
        "y",
        "end_x",
        "end_y",
        "x_oriented",
        "y_oriented",
        "end_x_oriented",
        "end_y_oriented",
        "event_type",
        "outcome",
        "phase",
        "phase_type",
        "interpretation_label",
        "insight_text",
        "dashboard_section",
        "recommended_chart_type",
        "priority_level",
    ]
    seen = set()
    ordered = []
    for field in first + fields:
        if field in fields and field not in seen:
            ordered.append(field)
            seen.add(field)
    return ordered


def write_standardized_existing(file_name: str) -> None:
    path = OUTPUTS / file_name
    fields, rows = read_csv(path)
    if not rows:
        return
    rows = add_tableau_metadata(rows, file_name)
    all_fields = sorted({field for row in rows for field in row})
    write_csv(path, preferred_field_order(all_fields), rows)


def load_events() -> list[dict[str, str]]:
    _, events = read_csv(EVENTS_FILE)
    return [row for row in events if is_action(row)]


def load_team_lookup() -> dict[str, str]:
    _, games = read_csv(GAMES_FILE)
    lookup: dict[str, str] = {}
    for game in games:
        home_id = game.get("home_team_id")
        away_id = game.get("away_team_id")
        if home_id and away_id:
            lookup[home_id] = game.get("away_team_name", "")
            lookup[away_id] = game.get("home_team_name", "")
    return lookup


def infer_event_type(row: dict[str, str]) -> str:
    if is_shot(row):
        return "shot"
    if is_pass(row):
        return "pass"
    if is_recovery(row):
        return "recovery"
    if is_loss(row):
        return "loss"
    return first_non_blank(row.get("outcome"), row.get("phase_type"), row.get("start_type"), row.get("coord_source"), "event")


def event_interpretation(row: dict[str, str], event_type: str) -> str:
    if event_type == "shot":
        return "shot attempt"
    if is_box(row):
        return "box involvement"
    if ends_final_third(row):
        return "final-third entry"
    if is_progressive(row):
        return "progressive action"
    if event_type == "loss":
        return "turnover / loss"
    if event_type == "recovery":
        return "ball recovery"
    return "context event"


def event_dashboard_section(row: dict[str, str], event_type: str) -> str:
    if event_type == "shot" or is_box(row):
        return "Chance Creation & Final Third"
    if event_type in {"loss", "recovery"}:
        return "Defensive Behaviour & Transitions"
    if is_progressive(row) or ends_final_third(row) or is_final_third(row):
        return "Territory & Control"
    return "Executive Match Overview"


def event_priority(row: dict[str, str], event_type: str) -> str:
    if event_type == "shot" or is_box(row) or is_loss(row):
        return "high"
    if is_progressive(row) or ends_final_third(row) or is_recovery(row):
        return "medium"
    return "low"


def build_event_map(events: list[dict[str, str]], opponent_lookup: dict[str, str]) -> None:
    rows: list[dict[str, Any]] = []
    for row in events:
        x = num(row.get("x_oriented"))
        y = num(row.get("y_oriented"))
        if x is None or y is None:
            continue
        event_type = infer_event_type(row)
        relevant = (
            event_type in {"shot", "pass", "recovery", "loss"}
            or is_box(row)
            or is_final_third(row)
            or ends_final_third(row)
            or is_progressive(row)
            or truthy(row.get("is_set_play"))
        )
        if not relevant:
            continue
        label = event_interpretation(row, event_type)
        team = row.get("team_name", "")
        rows.append(
            {
                "match_id": row.get("match_id", ""),
                "game_id_opta": row.get("game_id_opta", ""),
                "event_id": row.get("event_id", ""),
                "order": row.get("order", ""),
                "period": row.get("period", ""),
                "period_second": safe_round(row.get("period_second")),
                "match_second": safe_round(row.get("match_second")),
                "match_minute": row.get("match_minute", ""),
                "minute_bin_5": row.get("minute_bin_5", ""),
                "team_id": row.get("team_id", ""),
                "team_name": team,
                "opponent_team_id": row.get("opponent_team_id", ""),
                "opponent_team_name": first_non_blank(row.get("opponent_team_name"), opponent_lookup.get(row.get("team_id", ""))),
                "player_id": first_non_blank(row.get("player_id"), row.get("passer_id"), row.get("shooter_id")),
                "player_name": row.get("player_name", ""),
                "event_type": event_type,
                "outcome": first_non_blank(row.get("outcome"), row.get("shot_outcome"), row.get("raw_outcome")),
                "phase": first_non_blank(row.get("phase_type"), row.get("state"), row.get("start_type")),
                "third": row.get("third", ""),
                "zone": row.get("third", ""),
                "channel": row.get("channel", ""),
                "x": safe_round(row.get("x")),
                "y": safe_round(row.get("y")),
                "end_x": safe_round(row.get("end_x")),
                "end_y": safe_round(row.get("end_y")),
                "x_oriented": round(x, 4),
                "y_oriented": round(y, 4),
                "end_x_oriented": safe_round(row.get("end_x_oriented")),
                "end_y_oriented": safe_round(row.get("end_y_oriented")),
                "is_progressive": is_progressive(row),
                "is_final_third_entry": ends_final_third(row) and not is_final_third(row),
                "is_box_entry": is_box(row),
                "is_set_play": truthy(row.get("is_set_play")),
                "xg": safe_round(row.get("xg")),
                "threat_value": round(threat_value(row), 4),
                "interpretation_label": label,
                "insight_text": f"{team} {label} at minute {row.get('match_minute', '')}.",
                "dashboard_section": event_dashboard_section(row, event_type),
                "recommended_chart_type": "pitch scatter map",
                "priority_level": event_priority(row, event_type),
            }
        )
    rows = add_tableau_metadata(rows, "tableau_event_map.csv")
    fields = preferred_field_order(sorted({field for item in rows for field in item}))
    write_csv(OUTPUTS / "tableau_event_map.csv", fields, rows)


def build_shots(events: list[dict[str, str]], opponent_lookup: dict[str, str]) -> None:
    preferred = [row for row in events if is_shot_row_preferred(row)]
    if not preferred:
        preferred = [row for row in events if is_shot(row)]

    rows: list[dict[str, Any]] = []
    seen: set[tuple[str, str, str, str, str]] = set()
    for row in preferred:
        shot_key = (
            row.get("match_id", ""),
            row.get("team_name", ""),
            first_non_blank(row.get("shooter_id"), row.get("player_id")),
            f"{num(row.get('match_second')) or 0:.1f}",
            f"{num(row.get('xg')) or 0:.4f}",
        )
        if shot_key in seen:
            continue
        seen.add(shot_key)
        team = row.get("team_name", "")
        outcome = first_non_blank(row.get("shot_outcome"), row.get("raw_shot_outcome"), row.get("outcome"), "unknown")
        xg = num(row.get("xg")) or 0.0
        label = "high-value shot" if xg >= 0.12 else "medium-value shot" if xg >= 0.05 else "low-value shot"
        rows.append(
            {
                "match_id": row.get("match_id", ""),
                "game_id_opta": row.get("game_id_opta", ""),
                "event_id": row.get("event_id", ""),
                "period": row.get("period", ""),
                "period_second": safe_round(row.get("period_second")),
                "match_second": safe_round(row.get("match_second")),
                "match_minute": row.get("match_minute", ""),
                "minute_bin_5": row.get("minute_bin_5", ""),
                "team_id": row.get("team_id", ""),
                "team_name": team,
                "opponent_team_id": row.get("opponent_team_id", ""),
                "opponent_team_name": first_non_blank(row.get("opponent_team_name"), opponent_lookup.get(row.get("team_id", ""))),
                "player_id": first_non_blank(row.get("shooter_id"), row.get("player_id"), row.get("raw_shooter_id")),
                "player_name": row.get("player_name", ""),
                "event_type": "shot",
                "outcome": outcome,
                "shot_outcome": outcome,
                "is_goal": is_goal(row),
                "is_on_target": is_shot_on_target(row),
                "is_from_box": is_box(row),
                "xg": round(xg, 4),
                "shot_distance_m": safe_round(first_non_blank(row.get("raw_goal_dist"), row.get("raw_goal_distance"))),
                "shot_angle": safe_round(row.get("raw_angle")),
                "shot_technique": row.get("raw_shot_technique", ""),
                "set_play_type": row.get("set_play_type") or row.get("raw_shot_set_piece"),
                "phase": first_non_blank(row.get("phase_type"), row.get("start_type"), row.get("state")),
                "third": row.get("third", ""),
                "zone": first_non_blank(row.get("raw_shot_zone"), row.get("third")),
                "channel": row.get("channel", ""),
                "x_oriented": safe_round(row.get("x_oriented")),
                "y_oriented": safe_round(row.get("y_oriented")),
                "interpretation_label": label,
                "insight_text": f"{team} generated a {xg:.2f} xG shot ({outcome}) in minute {row.get('match_minute', '')}.",
            }
        )
    rows = add_tableau_metadata(rows, "tableau_shots.csv")
    fields = preferred_field_order(sorted({field for item in rows for field in item}))
    write_csv(OUTPUTS / "tableau_shots.csv", fields, rows)


def possession_attack_type(duration: float, actions: int, gain: float, shots: int, box_entries: int) -> str:
    if shots or box_entries:
        if duration <= 12 and gain >= 25:
            return "direct transition"
        return "chance-ending possession"
    if duration <= 10 and gain >= 20:
        return "direct attack"
    if actions >= 12 or duration >= 35:
        return "elaborate possession"
    if gain >= 20:
        return "progressive possession"
    return "maintenance possession"


def build_possession_sequences(events: list[dict[str, str]], opponent_lookup: dict[str, str]) -> None:
    grouped: dict[tuple[str, str, str], list[dict[str, str]]] = defaultdict(list)
    for row in events:
        poss_id = row.get("poss_id")
        if not poss_id:
            continue
        grouped[(row.get("match_id", ""), row.get("period", ""), poss_id)].append(row)

    rows: list[dict[str, Any]] = []
    for (match_id, period, poss_id), poss_events in grouped.items():
        poss_events.sort(key=lambda item: (num(item.get("match_second")) or 0.0, num(item.get("order")) or 0.0))
        team_counts = Counter(row.get("team_name", "") for row in poss_events if row.get("team_name"))
        if not team_counts:
            continue
        team = team_counts.most_common(1)[0][0]
        team_rows = [row for row in poss_events if row.get("team_name") == team]
        seconds = [num(row.get("match_second")) for row in team_rows if num(row.get("match_second")) is not None]
        if not seconds:
            continue
        start_second = min(seconds)
        end_second = max(seconds)
        duration = max(0.0, end_second - start_second)
        shots = sum(1 for row in team_rows if is_shot(row))
        shot_xg = sum(num(row.get("xg")) or 0.0 for row in team_rows if is_shot(row))
        final_entries = sum(1 for row in team_rows if ends_final_third(row) and not is_final_third(row))
        box_entries = sum(1 for row in team_rows if is_box(row))
        progressive_actions = sum(1 for row in team_rows if is_progressive(row))
        vertical_gain_m = sum(vertical_gain(row) for row in team_rows)
        threat = sum(threat_value(row) for row in team_rows)
        start_x_values = [num(row.get("x_oriented")) for row in team_rows if num(row.get("x_oriented")) is not None]
        end_x_values = [num(row.get("end_x_oriented")) for row in team_rows if num(row.get("end_x_oriented")) is not None]
        phase_counts = Counter(row.get("phase_type", "") for row in team_rows if row.get("phase_type"))
        start_type = first_non_blank(*(row.get("start_type") for row in team_rows[:5]))
        attack_type = possession_attack_type(duration, len(team_rows), vertical_gain_m, shots, box_entries)
        rows.append(
            {
                "match_id": match_id,
                "poss_id": poss_id,
                "team_name": team,
                "opponent_team_name": first_non_blank(opponent_lookup.get(team), next((row.get("opponent_team_name") for row in team_rows if row.get("opponent_team_name")), "")),
                "period": period,
                "start_match_second": round(start_second, 4),
                "end_match_second": round(end_second, 4),
                "duration_seconds": round(duration, 4),
                "start_minute": int(start_second // 60) + 1,
                "minute_bin_5": int(start_second // 300) * 5,
                "actions": len(team_rows),
                "passes": sum(1 for row in team_rows if is_pass(row)),
                "progressive_actions": progressive_actions,
                "vertical_gain_m": round(vertical_gain_m, 4),
                "start_x_oriented": round(start_x_values[0], 4) if start_x_values else "",
                "end_x_oriented": round(end_x_values[-1], 4) if end_x_values else "",
                "final_third_entries": final_entries,
                "box_entries": box_entries,
                "shots": shots,
                "xg": round(shot_xg, 4),
                "threat_value": round(threat, 4),
                "dominant_phase": phase_counts.most_common(1)[0][0] if phase_counts else "",
                "start_type": start_type,
                "attack_type": attack_type,
                "interpretation_label": attack_type,
                "insight_text": f"{team} possession lasted {duration:.1f}s, gained {vertical_gain_m:.1f}m and produced {shots} shots.",
            }
        )

    rows = add_tableau_metadata(rows, "tableau_possession_sequences.csv")
    fields = preferred_field_order(sorted({field for item in rows for field in item}))
    write_csv(OUTPUTS / "tableau_possession_sequences.csv", fields, rows)


def description_for_column(column: str) -> str:
    descriptions = {
        "match_id": "Stable match identifier used to relate all final outputs.",
        "game_id_opta": "Provider match identifier from the source data.",
        "event_id": "Stable event identifier where the row is event-level.",
        "poss_id": "Provider possession identifier; used as a possession proxy, not official possession.",
        "team_id": "Team identifier from the event or tracking source.",
        "team_name": "Team short name.",
        "team": "Team short name used by earlier metric outputs.",
        "opponent_team_id": "Opponent team identifier when available.",
        "opponent_team_name": "Opponent team short name.",
        "opponent": "Opponent team short name used by earlier metric outputs.",
        "period": "Match period or half.",
        "period_second": "Seconds elapsed within the current period.",
        "match_second": "Continuous match clock in seconds.",
        "match_minute": "Match minute derived from the continuous clock.",
        "minute_bin": "Time bucket used for Tableau timelines.",
        "minute_bin_5": "Five-minute time bucket.",
        "player_id": "Player identifier, usually Opta ID.",
        "player_name": "Player display name.",
        "metric_group": "Analytical family for player or team metrics.",
        "metric_name": "Machine-readable metric name.",
        "metric_value": "Numeric value of the metric.",
        "metric_unit": "Explicit unit for interpreting metric_value.",
        "zone": "Field zone or provider zone, depending on file granularity.",
        "third": "Defensive, middle or attacking third using oriented x coordinates.",
        "channel": "Left, central or right channel using oriented y coordinates.",
        "x_oriented": "Start x coordinate in meters, oriented so attack goes right.",
        "y_oriented": "Start y coordinate in meters, oriented so attack goes right.",
        "end_x_oriented": "End x coordinate in meters, oriented so attack goes right.",
        "end_y_oriented": "End y coordinate in meters, oriented so attack goes right.",
        "event_type": "Simplified event family for pitch maps.",
        "outcome": "Event or shot outcome when available.",
        "phase": "Provider phase/context simplified for analysis.",
        "interpretation_label": "Short football-reading label for Tableau color or annotation.",
        "insight_text": "Human-readable explanation for tooltip or annotation.",
        "dashboard_section": "Recommended dashboard page where the row belongs.",
        "recommended_chart_type": "Suggested Tableau chart type.",
        "priority_level": "High/medium/low priority for dashboard build order.",
    }
    return descriptions.get(column, column.replace("_", " ").capitalize())


def tableau_use_for_column(column: str) -> str:
    if column in {"metric_value", "xg", "threat_value", "duration_seconds", "vertical_gain_m"}:
        return "Measure"
    if column.endswith("_oriented") or column in {"x", "y", "end_x", "end_y"}:
        return "Pitch coordinate"
    if column in {"match_id", "event_id", "poss_id", "player_id", "team_id"}:
        return "Relationship key / detail"
    if column in {"interpretation_label", "insight_text"}:
        return "Tooltip / annotation"
    if column in {"dashboard_section", "recommended_chart_type", "priority_level"}:
        return "Dashboard organization"
    if "minute" in column or "second" in column or column == "period":
        return "Timeline filter / axis"
    return "Dimension / filter"


def infer_type(values: list[str]) -> str:
    sample = [value for value in values if value != ""][:50]
    if not sample:
        return "string"
    numeric = sum(num(value) is not None for value in sample)
    booleans = sum(value.lower() in {"true", "false"} for value in sample)
    if booleans == len(sample):
        return "boolean"
    if numeric == len(sample):
        return "number"
    return "string"


def file_granularity(file_name: str) -> str:
    if "match_summary" in file_name:
        return "one row per match-team-metric"
    if "team_period" in file_name:
        return "one row per match-team-period-metric"
    if "team_zone" in file_name:
        return "one row per match-team-zone-channel-metric"
    if "player_metrics" in file_name:
        return "one row per player-metric"
    if "player_profiles" in file_name:
        return "one row per player profile"
    if "event_map" in file_name:
        return "one row per relevant event"
    if "shots" in file_name:
        return "one row per shot attempt"
    if "possession" in file_name:
        return "one row per possession sequence"
    if "momentum" in file_name:
        return "one row per team-time-bin-metric"
    if "insight" in file_name:
        return "one row per detected insight flag"
    if "tracking_team_shape" in file_name:
        return "one row per team-time-bin-shape-metric"
    if "tracking_player_physical" in file_name:
        return "one row per player-physical-metric"
    return "Tableau-ready tidy output"


def write_data_dictionary(output_files: list[str]) -> None:
    lines = [
        "# Tableau Data Dictionary",
        "",
        "This dictionary documents the final Tableau-facing CSVs after `scripts/05_prepare_tableau_outputs.py` has standardized column names and metadata.",
        "",
    ]
    for file_name in output_files:
        path = OUTPUTS / file_name
        fields, rows = read_csv(path)
        if not fields:
            continue
        lines.extend(
            [
                f"## {file_name}",
                f"- **Granularity:** {file_granularity(file_name)}",
                "",
                "| column | type | description | recommended_tableau_use |",
                "|---|---|---|---|",
            ]
        )
        for field in fields:
            values = [row.get(field, "") for row in rows]
            lines.append(f"| `{field}` | {infer_type(values)} | {description_for_column(field)} | {tableau_use_for_column(field)} |")
        lines.append("")
    (DOCS / "tableau_data_dictionary.md").write_text("\n".join(lines), encoding="utf-8")


def write_calculated_fields() -> None:
    text = """# Tableau Calculated Fields

Use these formulas as implementation-ready Tableau calculated fields. Field names may need minor adjustment if Tableau aliases a column.

## Field Zones
```tableau
IF [x_oriented] >= 39.5 AND ABS([y_oriented]) <= 20.16 THEN "box"
ELSEIF [x_oriented] > 18.67 THEN "attacking_third"
ELSEIF [x_oriented] < -18.67 THEN "defensive_third"
ELSE "middle_third"
END
```

## Channels
```tableau
IF [y_oriented] < -13.33 THEN "left_channel"
ELSEIF [y_oriented] > 13.33 THEN "right_channel"
ELSE "central_channel"
END
```

## Minute Bins
```tableau
INT([match_second] / 300) * 5
```

## Metric Labels
```tableau
REPLACE(REPLACE([metric_name], "_", " "), "xg", "xG")
```

## Team Comparison Labels
```tableau
IF [metric_value] > WINDOW_AVG([metric_value]) THEN [team_name] + " above match average"
ELSEIF [metric_value] < WINDOW_AVG([metric_value]) THEN [team_name] + " below match average"
ELSE [team_name] + " level with match average"
END
```

## High / Medium / Low Thresholds
```tableau
IF [metric_value] >= WINDOW_PERCENTILE([metric_value], 0.75) THEN "high"
ELSEIF [metric_value] <= WINDOW_PERCENTILE([metric_value], 0.25) THEN "low"
ELSE "medium"
END
```

## Per 90 Metrics
```tableau
IF SUM([minutes_played]) > 0 THEN SUM([metric_value]) / SUM([minutes_played]) * 90 END
```

## Percentage Share Metrics
```tableau
SUM([metric_value]) / WINDOW_SUM(SUM([metric_value]))
```

## Momentum Index
```tableau
ZN(SUM(IF [metric_name] = "threat" THEN [metric_value] END)) * 3
+ ZN(SUM(IF [metric_name] = "box_entries" THEN [metric_value] END)) * 2
+ ZN(SUM(IF [metric_name] = "attacking_third_actions" THEN [metric_value] END))
```

## Danger Index
```tableau
ZN(SUM([xg])) * 4
+ ZN(SUM([threat_value])) * 2
+ ZN(SUM(IIF([is_from_box], 1, 0)))
+ ZN(SUM(IIF([is_on_target], 1, 0)))
```

## Direct vs Elaborate Attack
```tableau
IF [duration_seconds] <= 12 AND [vertical_gain_m] >= 25 THEN "direct transition"
ELSEIF [actions] >= 12 OR [duration_seconds] >= 35 THEN "elaborate possession"
ELSEIF [vertical_gain_m] >= 20 THEN "progressive possession"
ELSE "maintenance possession"
END
```
"""
    (DOCS / "tableau_calculated_fields.md").write_text(text, encoding="utf-8")


def build_docs(output_files: list[str]) -> None:
    write_data_dictionary(output_files)
    write_calculated_fields()


def main() -> None:
    OUTPUTS.mkdir(parents=True, exist_ok=True)
    DOCS.mkdir(parents=True, exist_ok=True)

    events = load_events()
    opponent_lookup = load_team_lookup()

    build_event_map(events, opponent_lookup)
    build_shots(events, opponent_lookup)
    build_possession_sequences(events, opponent_lookup)

    final_files = REQUIRED_OUTPUTS + [file_name for file_name in OPTIONAL_TRACKING_OUTPUTS if (OUTPUTS / file_name).exists()]
    for file_name in final_files:
        write_standardized_existing(file_name)

    build_docs(final_files)

    print("Final Tableau outputs prepared:")
    for file_name in final_files:
        path = OUTPUTS / file_name
        fields, rows = read_csv(path)
        print(f"- {file_name}: {len(rows)} rows, {len(fields)} columns")
    print("- docs/tableau_data_dictionary.md")
    print("- docs/tableau_calculated_fields.md")


if __name__ == "__main__":
    main()
